# Generated by Django 4.2.30 on 2026-05-06 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='caja_relacionada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alertas', to='core.caja'),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='medicamento_relacionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alertas', to='core.medicamento'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='testigo',
            field=models.ForeignKey(blank=True, help_text='Requerido para narcóticos y descartes', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_testigo', to=settings.AUTH_USER_MODEL),
        ),
    ]
