# Generated by Django 4.2.30 on 2026-06-03 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='conteo_final_confirmado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='turno',
            name='conteo_inicial_confirmado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='turno',
            name='firma_cierre',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='turno',
            name='firma_inicio',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='turno',
            name='notas_cierre',
            field=models.TextField(blank=True),
        ),
    ]
