# Generated by Django 4.2.30 on 2026-06-03 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_turno_conteo_final_confirmado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='conteo_fisico_final',
            field=models.JSONField(blank=True, default=list, help_text='Conteo físico reportado por paramédico al cierre'),
        ),
        migrations.AddField(
            model_name='turno',
            name='conteo_fisico_inicial',
            field=models.JSONField(blank=True, default=list, help_text='Conteo físico reportado por paramédico al inicio'),
        ),
        migrations.AddField(
            model_name='turno',
            name='discrepancias',
            field=models.JSONField(blank=True, default=list, help_text='Diferencias detectadas entre esperado y conteo físico'),
        ),
        migrations.AddField(
            model_name='turno',
            name='snapshot_final',
            field=models.JSONField(blank=True, default=list, help_text='Inventario esperado al cerrar turno'),
        ),
        migrations.AddField(
            model_name='turno',
            name='snapshot_inicial',
            field=models.JSONField(blank=True, default=list, help_text='Inventario del sistema al iniciar turno'),
        ),
    ]
