# Generated by Django 4.2.30 on 2026-06-03 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_turno_snapshots_discrepancias'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustodiaCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CHECKOUT', 'Checkout'), ('CHECKIN', 'Checkin'), ('TRANSFERENCIA', 'Transferencia de custodia')], max_length=20)),
                ('snapshot_contenido', models.JSONField(blank=True, default=list, help_text='Inventario del sistema al momento del evento')),
                ('conteo_fisico', models.JSONField(blank=True, default=list, help_text='Conteo físico reportado')),
                ('discrepancias', models.JSONField(blank=True, default=list)),
                ('firma_origen', models.CharField(blank=True, max_length=64)),
                ('firma_destino', models.CharField(blank=True, max_length=64)),
                ('notas', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custodias', to='core.caja')),
                ('usuario_destino', models.ForeignKey(help_text='Quién recibe la caja', on_delete=django.db.models.deletion.PROTECT, related_name='custodias_recibidas', to=settings.AUTH_USER_MODEL)),
                ('usuario_origen', models.ForeignKey(blank=True, help_text='Quién entrega la caja', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custodias_entregadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'custodia_cajas',
                'ordering': ['-timestamp'],
            },
        ),
    ]
