# Generated by Django 4.2.30 on 2026-06-03 03:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_custodia_caja'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DANO', 'Daño de medicamento'), ('PERDIDA', 'Pérdida / faltante'), ('DISCREPANCIA', 'Discrepancia de inventario'), ('DESCARTE_INCOMPLETO', 'Descarte incompleto'), ('DESVIO', 'Posible desvío'), ('VENCIMIENTO', 'Medicamento vencido no retirado'), ('OTRO', 'Otro')], max_length=25)),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('EN_INVESTIGACION', 'En investigación'), ('PENDIENTE_APROBACION', 'Pendiente de aprobación'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=25)),
                ('severidad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=10)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('causa_raiz', models.TextField(blank=True)),
                ('acciones_correctivas', models.TextField(blank=True)),
                ('evidencia_urls', models.JSONField(blank=True, default=list, help_text='URLs de evidencia fotográfica o documental')),
                ('cantidad_afectada', models.PositiveIntegerField(default=0)),
                ('lote_afectado', models.CharField(blank=True, max_length=50)),
                ('resolucion', models.TextField(blank=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('alerta_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes', to='core.alerta')),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidentes_aprobados', to=settings.AUTH_USER_MODEL)),
                ('caja_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidentes', to='core.caja')),
                ('investigador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidentes_asignados', to=settings.AUTH_USER_MODEL)),
                ('medicamento_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidentes', to='core.medicamento')),
                ('reportado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidentes_reportados', to=settings.AUTH_USER_MODEL)),
                ('transaccion_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidentes', to='core.transaccion')),
            ],
            options={
                'db_table': 'incidentes',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
