# Generated by Django 4.2.30 on 2026-06-04 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_incidente'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='hash_anterior',
            field=models.CharField(blank=True, default='GENESIS', help_text='Hash de la transacción anterior — forma cadena inmutable', max_length=64),
        ),
    ]
