# Generated by Django 4.2.30 on 2026-06-04 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_hash_anterior'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='timestamp',
            field=models.DateTimeField(db_index=True),
        ),
    ]
