# Generated by Django 4.2.30 on 2026-06-07 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_base_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cajas', to='core.base'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cajas_responsable', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='caja',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='caja',
            name='unidad',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
