# Generated by Django 4.2.30 on 2026-06-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_ndc_fecha_caducidad_hash_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='tipo',
            field=models.CharField(choices=[('RECEIPT', 'Recepción/Compra'), ('PICKUP', 'Recolección'), ('TRANSFER', 'Transferencia'), ('RETURN', 'Devolución'), ('WASTE', 'Descarte'), ('ADMINISTRATION', 'Administración'), ('DAMAGE', 'Daño/Incidencia'), ('INVENTORY', 'Ajuste de Inventario')], max_length=20),
        ),
    ]
