# Generated by Django 4.2.30 on 2026-06-13 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_receipt_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocoloAcuse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(db_index=True, help_text='Identificador del protocolo, ej. eliminacion-controlados', max_length=100)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acuses_protocolo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'protocolo_acuses',
                'ordering': ['-timestamp'],
                'unique_together': {('usuario', 'protocolo', 'version')},
            },
        ),
    ]
